# Site settings
title: Articles about compoter science
email: tayyar.besik@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Collected articles about Computer Science. All articles willb e hosted as plain and readable format.
baseurl: "/articles"
url: "http://hasantayyar.github.io/" # will be articles.lesson.im later
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
